### PR TITLE
1124-2021 Building & Deploying Web Apps with SASjs CLI

### PR DESCRIPTION
**Pull request by allanbowe**
This PR is dependent on #11 - if this is not to be merged, then we can close this PR, and I will remove the extra files and submit just the README / PDF

### CODE REVIEW

**Comment by cjdinger** [comment]
I merged #11 but now there's a conflict with this one in a README, @allanbowe

**Comment by allanbowe** [comment]
@cjdinger  - resolved!

**Comment by cj13579** [comment]
@allanbowe remember you still need to upload the PDF and update the SGF proceedings on SAS Communities. But great to see this openly committed here too. Thanks for contributing to the community!

**Comment by allanbowe** [comment]
Done - thanks for the reminder !

https://communities.sas.com/t5/SAS-Global-Forum-Proceedings/Scaffolding-SAS-Projects-With-NPM-and-SASjs/ta-p/726347

**Pull request merged**
